# NOTE - may need to restart nix-daemon on changes: `systemctl restart nix-daemon`

# Enable flakes and the new 'nix' CLI commands
experimental-features = nix-command flakes

# Optimizes the store automatically by hardlinking duplicate files
auto-optimise-store = true

# Allows you to use binary caches smoothly
trusted-users = root leander

# Prevent Nix from deleting build dependencies during garbage collection
# Great if you use devShells often so you don't have to re-download tools
#keep-outputs = true
#keep-derivations = true

# Fallback to building from source if a binary cache download fails
#fallback = true
