background {
  monitor =
  color = rgba(1e1e2eff)
}

input-field {
  monitor =
  size = 320, 48
  position = 0, -80
  halign = center
  valign = center
  outline_thickness = 2
  dots_center = true
  fade_on_empty = false
  placeholder_text = Password
  font_color = rgb(cdd6f4)
  inner_color = rgba(313244cc)
  outer_color = rgba(cba6f7ff)
  check_color = rgb(a6e3a1)
  fail_color = rgb(f38ba8)
}
