# inclues
include current-theme.conf

# fonts
font_family         JetBrainsMono Nerd Font
font_size           10.0
modify_font         cell_height 120%
disable_ligatures   never

# cursor
cursor_shape            block
cursor_blink_interval   0.5

# misc
term                xterm-256color
shell_integration   no-cursor no-title

# remote
allow_remote_control    yes
listen_on               unix:/tmp/kitty

# window
confirm_os_window_close 0
window_padding_width    6
scrollback_lines        100000
enabled_layouts         tall, fat, grid, stack

# tab bar
tab_bar_min_tabs    0
tab_bar_edge        top
tab_bar_style       powerline
tab_powerline_style slanted
tab_bar_filter      session:~ or session:^$
tab_title_template  " {index}.{session_name} {title} "

# mapping
kitty_mod ctrl+shift

#map ctrl+shift+f show_scrollback
map ctrl+backspace send_text all \x17
map ctrl+shift+enter new_window_with_cwd
map ctrl+shift+n new_os_window_with_cwd
map ctrl+shift+t new_tab_with_cwd
map ctrl+shift+f toggle_layout stack

# overlays
map alt+t launch --title='term overlay' --type=overlay
map alt+b launch --title='btop overlay' --type=overlay btop
map alt+g launch --title='lazygit overlay' --type=overlay lazygit

# session
startup_session sessions/home.session

map f5 save_as_session --relocatable --use-foreground-process --match=session:. .
map ctrl+f launch --title='sessionizer' --type=overlay '$HOME/.config/kitty/scripts/sessionizer.sh'
map ctrl+h launch --title='sessionizer' --type=overlay '$HOME/.config/kitty/scripts/sessionizer.sh --list'
map ctrl+a launch --type=background "$HOME/.config/kitty/scripts/sessionizer.sh --add"

#map ctrl+shift+q --- close session

#map alt+1 launch --type=background '$HOME/.config/kitty/scripts/sessionizer.sh --nav 1'
#map alt+1 launch --type=overlay ~/bin/kss --nav 1
#map alt+2 launch --type=overlay ~/bin/kss --nav 2
#map alt+3 launch --type=overlay ~/bin/kss --nav 3
#map alt+4 launch --type=overlay ~/bin/kss --nav 4

# goto tab
map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab 9
map alt+0 goto_tab 0

# Optional: Program to view the scrollback buffer in a separate window
# Press Ctrl+Shift+H to open your current scrollback in Neovim!
#scrollback_pager nvim -c "set noreadonly" -c "set buftype=nofile" -
