# inclues
include current-theme.conf

# fonts
font_family         JetBrainsMono Nerd Font
font_size           10.0
modify_font         cell_height 120%
disable_ligatures   never

# cursor
cursor_shape            block
cursor_blink_interval   0.5

# misc
shell_integration       no-cursor no-title
update_check_interval   24

# remote
allow_remote_control    yes
listen_on               unix:/tmp/kitty

# window
confirm_os_window_close 0
window_padding_width    6
scrollback_lines        100000
enabled_layouts         tall, fat, grid, stack

# tab bar
tab_bar_min_tabs    0
tab_bar_edge        top
tab_bar_style       powerline
tab_powerline_style slanted
tab_bar_filter      session:~ or session:^$
tab_title_template  " {session_name+' 󱓞 ' if index==1 else ''}{title} "

# mapping
kitty_mod ctrl+shift

#map ctrl+shift+f show_scrollback
map ctrl+backspace send_text all \x17
map ctrl+shift+enter new_window_with_cwd
map ctrl+shift+n new_os_window_with_cwd
map ctrl+shift+t new_tab_with_cwd
map ctrl+shift+f toggle_layout stack
map ctrl+shift+, move_tab_forward
map ctrl+shift+. move_tab_backward

# overlays
map alt+t launch --title='term overlay' --type=overlay
map alt+b launch --title='btop overlay' --type=overlay btop
map alt+g launch --title='lazygit overlay' --type=overlay lazygit

# session
startup_session $HOME/.config/kitty/sessions/home.kitty-session

map f5 save_as_session --relocatable --use-foreground-process --match=session:. .

map ctrl+shift+q close_session .
map ctrl+shift+f launch --type=overlay $HOME/.config/kitty/scripts/sessionizer.sh

map ctrl+shift+0 launch --type=overlay kitten @ action goto_session $HOME/.config/kitty/sessions/home.session
map ctrl+shift+1 launch --type=overlay $HOME/.config/kitty/scripts/sessionizer.sh jump 1
map ctrl+shift+2 launch --type=overlay $HOME/.config/kitty/scripts/sessionizer.sh jump 2
map ctrl+shift+3 launch --type=overlay $HOME/.config/kitty/scripts/sessionizer.sh jump 3
map ctrl+shift+4 launch --type=overlay $HOME/.config/kitty/scripts/sessionizer.sh jump 4
map ctrl+shift+5 launch --type=overlay $HOME/.config/kitty/scripts/sessionizer.sh jump 5

# goto tab
map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5

# Optional: Program to view the scrollback buffer in a separate window
# Press Ctrl+Shift+H to open your current scrollback in Neovim!
#scrollback_pager nvim -c "set noreadonly" -c "set buftype=nofile" -
